services:
  - type: web
    name: resumelens-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  - type: web
    name: resumelens-ml
    env: python
    region: oregon
    plan: starter
    buildCommand: cd ml-service && python -m pip install --upgrade pip setuptools wheel && pip install --prefer-binary -r requirements.txt
    startCommand: cd ml-service && gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 5001
